name: iOS Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  ios-build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS (Debug)
        run: |
          cd ios
          xcodebuild -workspace digbiz5.xcworkspace \
                     -scheme digbiz5 \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     -derivedDataPath build \
                     build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: ios/build/
          retention-days: 30